import { React, useState, useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
function WhatOffset() {
  const [offsets, setOffsets] = useState([]);
  const stop = "stop";
  let Offsets = [
    {
      qst: "Farm Power",
      ans:
        "Terrapass works with farms in communities across the United States to make the best possible use of animal waste.  Through the use of anaerobic digesters, methane is captured as the manure breaks down and is then destroyed when it is burned as a fuel to produce electricity.  Additionally, these digesters can produce a variety of other products that help the farm and reduce environmental impact. The fibrous material can be separated, dried, and used as bedding, while the liquid effluent can be used as fertilizer.  Anaerobic digestion also aids local communities by helping to reduce water pollution and odor associated with animal husbandry.",
      isTrue: false,
      aos: "fade-up",
      time: "2000",
    },
    {
      qst: "Landfull Gas Capture",
      ans:
        "Landfill gas capture projects turn garbage into power. As organic waste breaks down, it releases methane, a greenhouse gas 84 times more powerful than CO2. According to the EPA, landfills are the third largest source of methane emissions in the United States. Through the installation of gas collection and control systems, these projects result in the destruction of powerful greenhouse gases, and the gas can be burned in a generator to create renewable electricity.",
      isTrue: false,
      aos: "fade-up",
      time: "2200",
    },
    {
      qst: "Clean Energy From Wind Power",
      ans:
        "Wind energy displaces electricity that is generated by dirty fossil fuels like gas and coal (the way that most power is currently generated in the United States). In this sense, the amount of carbon dioxide emissions that are avoided depends upon the “carbon profile” of the electricity grid where the energy is produced. The carbon profile of each regional grid is calculated periodically by the US Environmental Protection Agency by adding up the weighted average of carbon dioxide emissions from all commercial energy sources on that regional grid.",
      isTrue: false,
      aos: "fade-up",
      time: "2400",
    },
    {
      qst: "Improved Forest Management",
      ans:
        "Forests can sequester carbon dioxide (C02) in a variety of ways. Carbon is stored in the trunks, leaves, branches, and roots of trees. Carbon is also stored in the forest soil, understory plants, and green “litter” on the forest floor. An Improved Forest Management Project under the CAR Forest Project Protocol involves changing forest management practices to increase carbon stocks on forested land relative to baseline (or “business as usual”) levels of carbon stocks. In other words, Improved Forest Management helps forests sequester more carbon.",
      isTrue: false,
      aos: "fade-up",
      time: "2600",
    },
  ];
  useEffect(() => {
    AOS.init();
    setOffsets(Offsets);
  }, []);

  const handleFaq = (index) => {
    Offsets[index].isTrue || offsets[index].isTrue
      ? (Offsets[index].isTrue = false)
      : (Offsets[index].isTrue = true);

    setOffsets(Offsets);
  };

  return (
    <div className="w-full flex flex-col px-10 lg:px-20 py-20">
      <div className="text-xl sm:text-4xl text-center mt-10 font-header font-bold">
        What types of carbon offsets does terrapass support?
      </div>
      <div className="flex flex-col mt-20">
        {Array.isArray(offsets) &&
          offsets.map((offset, index) => {
            const { qst, ans, isTrue, aos, time } = offset;
            return (
              <div
                className="flex flex-col border-t p-5"
                key={index}
                data-aos={aos}
                data-aos-anchor-placement="top-bottom"
                data-aos-duration={time}
              >
                <div
                  className=" hover:text-primary transition-all duration-300 ease-linear cursor-pointer font-bold flex justify-between"
                  onClick={() => {
                    handleFaq(index);
                  }}
                >
                  <div className="text-lg lg:text-3xl"> {qst}</div>
                  <div>
                    <svg
                      className="w-6 h-6"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </div>
                </div>
                <div
                  className={`text-sm lg:text-lg text-gray-600 transition-all duration-300 ease-linear  overflow-hidden ${
                    isTrue ? "h-44 md:h-36" : "h-0"
                  }`}
                >
                  {ans}
                </div>
              </div>
            );
          })}
      </div>
    </div>
  );
}

export default WhatOffset;
